src/Entity/Army.php
<?php

namespace App\Entity;

use App\Repository\ArmyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArmyRepository::class)
 */
class Army
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $limit_cost;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $total_cost;

    /**
     * @ORM\ManyToOne(targetEntity=Commander::class, inversedBy="armies")
     */
    private $commander;

    /**
     * @ORM\OneToMany(targetEntity=NoCombatUnit::class, mappedBy="army")
     */
    private $link_ncu;



    /**
     * @ORM\ManyToOne(targetEntity=Faction::class, inversedBy="armies")
     */
    private $faction;



    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="armies")
     * @ORM\JoinColumn(nullable=false)
     */
    private $armyUser;

    /**
     * @ORM\OneToMany(targetEntity=LineArmy::class, mappedBy="army", orphanRemoval=true)
     */
    private $lineArmies;

    /**
     * @ORM\ManyToMany(targetEntity=CombatUnit::class, inversedBy="armies")
     */
    private $linkCombatUnit;

    /**
     * @ORM\OneToMany(targetEntity=LineAttachment::class, mappedBy="army")
     */
    private $lineAttachments;



    /**
     * @ORM\OneToMany(targetEntity=LineNCU::class, mappedBy="army")
     */
    private $lineNCUs;

    /**
     * @ORM\ManyToMany(targetEntity=NoCombatUnit::class, inversedBy="armies")
     */
    private $linkNCU;

    /**
     * @ORM\OneToMany(targetEntity=LineCommander::class, mappedBy="army")
     */
    private $lineCommanders;





    public function __construct()
    {
        $this->link_ncu = new ArrayCollection();
        $this->link_combatUnit = new ArrayCollection();
        $this->lineArmies = new ArrayCollection();
        $this->combatUnits = new ArrayCollection();
        $this->linkCombatUnit = new ArrayCollection();
        $this->lineAttachments = new ArrayCollection();
        $this->linkNCU = new ArrayCollection();
        $this->lineNCUs = new ArrayCollection();
        $this->lineCommanders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLimitCost(): ?int
    {
        return $this->limit_cost;
    }

    public function setLimitCost(int $limit_cost): self
    {
        $this->limit_cost = $limit_cost;

        return $this;
    }

    public function getTotalCost(): ?int
    {
        return $this->total_cost;
    }

    public function setTotalCost(?int $total_cost): self
    {
        $this->total_cost = $total_cost;

        return $this;
    }

    public function getCommander(): ?Commander
    {
        return $this->commander;
    }

    public function setCommander(?Commander $commander): self
    {
        $this->commander = $commander;

        return $this;
    }





    public function getFaction(): ?Faction
    {
        return $this->faction;
    }

    public function setFaction(?Faction $faction): self
    {
        $this->faction = $faction;

        return $this;
    }



    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getArmyUser(): ?User
    {
        return $this->armyUser;
    }

    public function setArmyUser(?User $armyUser): self
    {
        $this->armyUser = $armyUser;

        return $this;
    }

    /**
     * @return Collection<int, LineArmy>
     */
    public function getLineArmies(): Collection
    {
        return $this->lineArmies;
    }

    public function addLineArmy(LineArmy $lineArmy): self
    {
        if (!$this->lineArmies->contains($lineArmy)) {
            $this->lineArmies[] = $lineArmy;
            $lineArmy->setArmy($this);
        }

        return $this;
    }

    public function removeLineArmy(LineArmy $lineArmy): self
    {
        if ($this->lineArmies->removeElement($lineArmy)) {
            // set the owning side to null (unless already changed)
            if ($lineArmy->getArmy() === $this) {
                $lineArmy->setArmy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CombatUnit>
     */
    public function getLinkCombatUnit(): Collection
    {
        return $this->linkCombatUnit;
    }

    public function addLinkCombatUnit(CombatUnit $linkCombatUnit): self
    {
        if (!$this->linkCombatUnit->contains($linkCombatUnit)) {
            $this->linkCombatUnit[] = $linkCombatUnit;
        }

        return $this;
    }

    public function removeLinkCombatUnit(CombatUnit $linkCombatUnit): self
    {
        $this->linkCombatUnit->removeElement($linkCombatUnit);

        return $this;
    }

    /**
     * @return Collection<int, LineAttachment>
     */
    public function getLineAttachments(): Collection
    {
        return $this->lineAttachments;
    }

    public function addLineAttachment(LineAttachment $lineAttachment): self
    {
        if (!$this->lineAttachments->contains($lineAttachment)) {
            $this->lineAttachments[] = $lineAttachment;
            $lineAttachment->setArmy($this);
        }

        return $this;
    }

    public function removeLineAttachment(LineAttachment $lineAttachment): self
    {
        if ($this->lineAttachments->removeElement($lineAttachment)) {
            // set the owning side to null (unless already changed)
            if ($lineAttachment->getArmy() === $this) {
                $lineAttachment->setArmy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LineNCU>
     */
    public function getLineNCUs(): Collection
    {
        return $this->lineNCUs;
    }

    public function addLineNCUs(LineNCU $lineNCUs): self
    {
        if (!$this->lineNCUs->contains($lineNCUs)) {
            $this->lineNCUs[] = $lineNCUs;
            $lineNCUs->setArmy($this);
        }

        return $this;
    }

    public function removeLineNCUs(LineNCU $lineNCUs): self
    {
        if ($this->lineNCUs->removeElement($lineNCUs)) {
            // set the owning side to null (unless already changed)
            if ($lineNCUs->getArmy() === $this) {
                $lineNCUs->setArmy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, NoCombatUnit>
     */
    public function getLinkNCU(): Collection
    {
        return $this->linkNCU;
    }

    public function addLinkNCU(NoCombatUnit $linkNCU): self
    {
        if (!$this->linkNCU->contains($linkNCU)) {
            $this->linkNCU[] = $linkNCU;
        }

        return $this;
    }

    public function removeLinkNCU(NoCombatUnit $linkNCU): self
    {
        $this->linkNCU->removeElement($linkNCU);

        return $this;
    }

    /**
     * @return Collection<int, LineCommander>
     */
    public function getLineCommanders(): Collection
    {
        return $this->lineCommanders;
    }

    public function addLineCommander(LineCommander $lineCommander): self
    {
        if (!$this->lineCommanders->contains($lineCommander)) {
            $this->lineCommanders[] = $lineCommander;
            $lineCommander->setArmy($this);
        }

        return $this;
    }

    public function removeLineCommander(LineCommander $lineCommander): self
    {
        if ($this->lineCommanders->removeElement($lineCommander)) {
            // set the owning side to null (unless already changed)
            if ($lineCommander->getArmy() === $this) {
                $lineCommander->setArmy(null);
            }
        }

        return $this;
    }

 


}

src/Form/ArmyType.php
<?php

namespace App\Form;

use App\Entity\Army;
use App\Entity\Faction;
use App\Entity\Commander;
use App\Entity\CombatUnit;

use App\Entity\NoCombatUnit;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class ArmyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
         ->add('faction', EntityType::class, [
            'class'=>Faction::class,
            'choice_label'=>'name',
            'label_attr'=>['class'=>'me-1'],
            'label'=>'Choisissez une faction',
            'placeholder' => 'xxxxxxxxxxx',

            'required'=>true,
        ]) 
             ->add('name', TextType::class, [
                "attr"=>[
                    'class'=>'form-control',
                ],
            ])

         
           // ->add('limit_cost')
            //->add('total_cost')
           // ->add('commander')
           ->add('commander', EntityType::class, [
            'class'=>Commander::class,
            'choice_label'=>'cardVerso',
            "attr"=>[
                'class'=>'form-control',
                ],
   
            'choice_attr'=>function($choice) {
                return ['data-faction' => $choice->getFaction()->getId()];
            },

            'label_attr'=>['class'=>'me-1'],
            'label'=>'Choisir un commandant',
            //'multiple' => true,
            'expanded'=>true,
            'required'=>true,


        ])
        ->add('quatro_stuff_add_btn', SubmitType::class, [
            'attr' => ['class' => 'quatro_stuff_add_btn'],
            'label' => 'Add Item',
        ])
/*---------------------------V1-------------------------------------------------------*/           
         ->add('linkCombatUnit', EntityType::class, [
            'class'=>CombatUnit::class,
            'choice_label'=>'cardVerso',
            "attr"=>[
                'class'=>'form-control',
                ],
            'placeholder'=>'choisir unité de combat',    
            'choice_attr'=>function($choice) {
                return ['data-faction' => $choice->getFaction()->getId()];
            },

            'label_attr'=>['class'=>'me-1'],
            'label'=>'Choisir une unité de combat',
            'multiple' => true,
            'expanded'=>true,
            'required'=>false,


        ])
/*------------------------------------------------------------------------------------*/
/*-------------------V2---------------------------------------------------------------*/ 
/*         ->add('linkCombatUnit', ChoiceType::class, [
            'placeholder'=>'Choisir une unité de combat',

        ]) */
/*-------------------------------------------------------------------------------------*/
        ->add('secondary_stuff_add_btn', SubmitType::class, [
                'attr' => ['class' => 'secondary_stuff_add_btn'],
                'label' => 'Add Item',
            ])

          ->add('linkNCU', EntityType::class, [
              "attr"=>[
                  'class'=>'form-control',
                  ],
              'class'=>NoCombatUnit::class,
              'choice_label'=>'cardVerso',
              'choice_attr'=>function($choice) {
                return ['data-faction' => $choice->getFaction()->getId()];
                },
              'label_attr'=>['class'=>'me-1'],
              'label'=>'Choisir une unité non combattante',
              'multiple' => true,
              'expanded'=>true,
              'required'=>false,
          ])
            ->add('tertiary_stuff_add_btn', SubmitType::class, [
                'attr' => ['class' => 'tertiary_stuff_add_btn'],
                'label' => 'Add Item',
            ])
            ->add('save', SubmitType::class, [
                'attr' => ['class' => 'save'],
                'label' => 'Save',
            ]);
/*----------------------V2-------------------------------------------------------------------*/            
/*             $formModifier = function(FormInterface $form, Faction $faction = null){
                $CUlist = null ===  $faction ? [] : $faction->getCombatUnits(); 
                $form->add('linkCombatUnit', EntityType::class, [
                    'class'=> CombatUnit::class,
                    'choices'=>$Culist,
                    "attr"=>[
                        'class'=>'form-control',
                        ],
                        'choice_label'=>'name',
              
                        'label_attr'=>['class'=>'me-1'],
                        'label'=>'Choisir une unité de combat',
                        'multiple' => true,
                       'expanded'=>true,
                        'required'=>false,
                    ]);
            };  
             $builder->get('faction')->addEventListener(
                FormEvents::POST_SUBMIT,
                function(formEvent $event) use ($formModifier){
                    $faction=$event->getForm()->getData();
                    $formModifier($event->getForm()->getParent(), $faction);

                }
            );
 */
/*-------------------------------------------------------------------------------------------------*/
/*-------------------------------------V3----------------------------------------------------------*/            
 

/*             $formModifier = function (FormInterface $form, Faction $faction = null){
                $CUlist = null === $faction ? [] : $faction->getCombatUnits();
                var_dump($CUlist);
                $form->add('linkCombatUnit', EntityType::class, [
                    'class'=>CombatUnit::class,
                    'placeholder'=>'',
                    'choices'=>$CUlist,
                    'choice_label'=>'name',
                    'multiple' => true,
                    'expanded'=>true,
                     'required'=>false,
                    'mapped'=>false,
                ]);
            };
            $builder->addEventListener(
                FormEvents::PRE_SET_DATA,
                function (FormEvent $event) use ($formModifier) {
                    $data=$event->getData();
                    $formModifier($event->getForm(), $data->getFaction());
                }

            );
            $builder->get('faction')->addEventListener(
                FormEvents::POST_SUBMIT,
                function (FormEvent $event) use ($formModifier){
                    $faction = $event->getForm()->getData();
                    $formModifier($event->getForm()->getParent(), $faction);
                }
            );
            $builder->setAction($options['action']);  */

/*---------------------------------------------------------------------------------------------------------------*/
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([

            'data_class' => Army::class,
        ]);
    }
}

templates/army/_delete_form.html.twig
<form method="post" action="{{ path('app_army_delete', {'id': army.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ army.id) }}">
    <button class="btn">Delete</button>
</form>

templates/army/_form.html.twig
{{ form_start(form, { attr: { id: 'myForm' } } ) }}
     {{ form_widget(form) }} 

{{ form_end(form) }}

templates/army/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Army{% endblock %}

{% block body %}
<main>
    <h1>Edit Army</h1>
    <p class='factionElement' data-faction='{{ army.faction.id }}'>Faction : {{ army.faction }}</p>

    {% if army.commander %}
        <p class='commanderElement' data-commander='{{ army.commander.id }}'>Commandant : {{ army.commander.name }}</p>
    {% endif %}

    {{ include('army/_form.html.twig', {'button_label': 'Update'}) }}
    <p>Coût total de l'armée : {{ totalCostCu }} points</p>
        <table class="table">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Name of unit</th>
                <th>Card</th>
                <th>cost</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% set display = false %}
        {% for lineArmy in lineArmies %}
            <tr>
                <td>{{ lineArmy.combatUnit.name }}</td>
                <td>{{ lineArmy.combatUnit.cardVerso }}<img class='cardToEnlarge' src="{{ asset('/uploads/image_cards/' ~ lineArmy.combatUnit.cardVerso) }}" alt="" ></td>
                <td>{{ lineArmy.combatUnit.cost }}</td>
                <td>
                    {% if lineArmy.lineCommander is not null %}
                    {% set display = true %}
                    {% endif %}
                    {% if lineArmy.lineCommander is null and display == false %}


                     <a href="{{ path('app_line_army_commander_edit', {'id': lineArmy.id}) }}">Add Commander</a>

                     {% endif %}
                     {% if lineArmy.lineAttachments|length < 1 and lineArmy.lineCommander is null %}
                        <a href="{{ path('app_line_army_edit', {'id': lineArmy.id}) }}">Add Attachment</a>
                    {% endif %}
                     <a href="{{ path('app_line_army_delete2', {'id': lineArmy.id}) }}">Delete Unit</a>
                    {# <a href="{{ path('app_army_edit', {'id': army.id}) }}">edit</a>  #}
                </td>
            </tr>
            {% for lineAttachment in lineAttachments %}
                {% if lineAttachment.lineArmy == lineArmy %}
                    <tr>
                    <td>&#x2794 Attachment &#x2794 {{ lineAttachment.attachment.name }}</td>
                    <td> {{ lineAttachment.attachment.cardVerso }}<img class='cardToEnlarge' src="{{ asset('/uploads/image_cards/' ~ lineAttachment.attachment.cardVerso) }}" alt="" ></td>
                    <td>{{ lineAttachment.attachment.cost }}</td>
                    <td><a href="{{ path('app_line_attachment_delete2', {'id': lineAttachment.id}) }}">Delete Attachment</a></td>
                    </tr>

                
                {% endif %}
            {% endfor %}
            {% for myLineCommander in lineCommander %}
                {% if myLineCommander.linkLineArmy == lineArmy %}
                    <tr>
                    <td>&#x2794 Commandant &#x2794 {{ myLineCommander.commander.name }}</td>
                    <td>{{ myLineCommander.commander.cardVerso }}<img class='cardToEnlarge' src="{{ asset('/uploads/image_cards/' ~ myLineCommander.commander.cardVerso) }}" alt="" ></td>
                    <td>{{ myLineCommander.commander.cost }}</td>
                    <td><a href="{{ path('app_line_commander_delete2', {'id': myLineCommander.id}) }}">Delete Commander</a></td>
                    </tr>

                
                {% endif %}
            {% endfor %}
 

        {# {% else %} #}
        {% endfor %}
        {% for lineNCU in lineNCUs %}
        <tr>
            <td>{{ lineNCU.noCombatUnit.name }}</td>
            <td>{{ lineNCU.noCombatUnit.cardVerso }}<img class='cardToEnlarge' src="{{ asset('/uploads/image_cards/' ~ lineNCU.noCombatUnit.cardVerso) }}" alt="" ></td>
            <td>{{ lineNCU.noCombatUnit.cost }}</td>
            <td>                     <a href="{{ path('app_lineNCU_delete2', {'id': lineNCU.id}) }}">Delete NCU</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{{ path('app_army_index') }}">back to list</a>
<script src="{{ asset('/js/form_edit_army.js') }}"></script>
    {{ include('army/_delete_form.html.twig') }}
    </main>
{% endblock %}

templates/army/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Army index{% endblock %}

{% block body %}
<main>
    <h1>Army index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Limit_cost</th>
                <th>Total_cost</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for army in armies %}
            <tr>
                <td>{{ army.id }}</td>
                <td>{{ army.name }}</td>
                <td>{{ army.limitCost }}</td>
                <td>{{ army.totalCost }}</td>
                <td>
                    <a href="{{ path('app_army_show', {'id': army.id}) }}">show</a>
                    <a href="{{ path('app_army_edit', {'id': army.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_army_new') }}">Create new</a>
</main>
{% endblock %}

templates/army/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Army{% endblock %}

{% block body %}
<main>
    <h1>Create new Army</h1>

    {{ include('army/_form.html.twig') }}

    <a href="{{ path('app_army_index') }}">back to list</a>
    <script src="{{ asset('/js/form_new_army.js') }}"></script>
    </main>
{% endblock %}

templates/army/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Army{% endblock %}

{% block body %}
    <h1>Army</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ army.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ army.name }}</td>
            </tr>
            <tr>
                <th>Limit_cost</th>
                <td>{{ army.limitCost }}</td>
            </tr>
            <tr>
                <th>Total_cost</th>
                <td>{{ army.totalCost }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_army_index') }}">back to list</a>

    <a href="{{ path('app_army_edit', {'id': army.id}) }}">edit</a>

    {{ include('army/_delete_form.html.twig') }}
{% endblock %}