src/Entity/Attachment.php
<?php

namespace App\Entity;

use App\Repository\AttachmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AttachmentRepository::class)
 */
class Attachment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=CombatUnit::class, inversedBy="haveAttachment")
     */
    private $combatUnit;

    /**
     * @ORM\ManyToOne(targetEntity=Faction::class, inversedBy="attachments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $faction;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_a_character;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $full_name;

    /**
     * @ORM\Column(type="integer")
     */
    private $cost;

    /**
     * @ORM\ManyToOne(targetEntity=TypeOfUnit::class, inversedBy="attachments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $card;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cardVerso;

    /**
     * @ORM\OneToMany(targetEntity=LineAttachment::class, mappedBy="attachment")
     */
    private $lineAttachments;

    /**
     * @ORM\ManyToMany(targetEntity=LineArmy::class, mappedBy="attachments")
     */
    private $lineArmies;

    public function __construct()
    {
        $this->lineAttachments = new ArrayCollection();
        $this->lineArmies = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCombatUnit(): ?CombatUnit
    {
        return $this->combatUnit;
    }

    public function setCombatUnit(?CombatUnit $combatUnit): self
    {
        $this->combatUnit = $combatUnit;

        return $this;
    }

    public function getFaction(): ?Faction
    {
        return $this->faction;
    }

    public function setFaction(?Faction $faction): self
    {
        $this->faction = $faction;

        return $this;
    }

    public function isIsACharacter(): ?bool
    {
        return $this->is_a_character;
    }

    public function setIsACharacter(bool $is_a_character): self
    {
        $this->is_a_character = $is_a_character;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->full_name;
    }

    public function setFullName(?string $full_name): self
    {
        $this->full_name = $full_name;

        return $this;
    }

    public function getCost(): ?int
    {
        return $this->cost;
    }

    public function setCost(int $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getType(): ?TypeOfUnit
    {
        return $this->type;
    }

    public function setType(?TypeOfUnit $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCard(): ?string
    {
        return $this->card;
    }

    public function setCard(?string $card): self
    {
        $this->card = $card;

        return $this;
    }

    public function getCardVerso(): ?string
    {
        return $this->cardVerso;
    }

    public function setCardVerso(?string $cardVerso): self
    {
        $this->cardVerso = $cardVerso;

        return $this;
    }

    /**
     * @return Collection<int, LineAttachment>
     */
    public function getLineAttachments(): Collection
    {
        return $this->lineAttachments;
    }

    public function addLineAttachment(LineAttachment $lineAttachment): self
    {
        if (!$this->lineAttachments->contains($lineAttachment)) {
            $this->lineAttachments[] = $lineAttachment;
            $lineAttachment->setAttachment($this);
        }

        return $this;
    }

    public function removeLineAttachment(LineAttachment $lineAttachment): self
    {
        if ($this->lineAttachments->removeElement($lineAttachment)) {
            // set the owning side to null (unless already changed)
            if ($lineAttachment->getAttachment() === $this) {
                $lineAttachment->setAttachment(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, LineArmy>
     */
    public function getLineArmies(): Collection
    {
        return $this->lineArmies;
    }

    public function addLineArmy(LineArmy $lineArmy): self
    {
        if (!$this->lineArmies->contains($lineArmy)) {
            $this->lineArmies[] = $lineArmy;
            $lineArmy->addAttachment($this);
        }

        return $this;
    }

    public function removeLineArmy(LineArmy $lineArmy): self
    {
        if ($this->lineArmies->removeElement($lineArmy)) {
            $lineArmy->removeAttachment($this);
        }

        return $this;
    }
}

src/Form/AttachmentType.php
<?php

namespace App\Form;

use App\Entity\Faction;
use App\Entity\Attachment;
use App\Entity\TypeOfUnit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class AttachmentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('is_a_character', CheckboxType::class, [
                "attr"=>[
                    'class'=>'ms-2',
    
                ],
                'label'=>'Cet attachement est un personnage nommé',
                'mapped' => true,
                'required' => false
            ])
            ->add('full_name')
            ->add('cost')
            ->add('card', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize'=>'16384k',
                        'maxSizeMessage'=>'Taille de fichier trop grande',
                        'mimeTypes'=>[
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                            'image/svg',
                        ],
                        'mimeTypesMessage'=>'Extension de fichier invalide',
                    ])
                    ],
                'attr'=>[
                    'class'=>'form-control',
                ],
                'data_class'=>null,
            ])
            ->add('cardVerso', FileType::class, [
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize'=>'16384k',
                        'maxSizeMessage'=>'Taille de fichier trop grande',
                        'mimeTypes'=>[
                            'image/jpeg',
                            'image/jpg',
                            'image/png',
                            'image/svg',
                        ],
                        'mimeTypesMessage'=>'Extension de fichier invalide',
                    ])
                    ],
                'attr'=>[
                    'class'=>'form-control',
                ],
                'data_class'=>null,
            ])
            //->add('combatUnit')
            ->add('faction', EntityType::class, [
                'class'=>Faction::class,
                'choice_label'=>'name',
                'label_attr'=>['class'=>'me-1'],
                'label'=>'Faction',
                //'mapped'=>false
            ])
            ->add('type', EntityType::class, [
                'class'=>TypeOfUnit::class,
                'choice_label'=>'name',
                'label_attr'=>['class'=>'me-1'],
                'label'=>'Type d\'unité',
                //'mapped'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Attachment::class,
        ]);
    }
}

src/Controller/AttachmentController.php
<?php

namespace App\Controller;

use App\Entity\Attachment;
use App\Form\AttachmentType;
use App\Service\FileUploader;
use App\Repository\RegionRepository;
use App\Repository\AttachmentRepository;
use App\Repository\NotificationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/attachment")
 */
class AttachmentController extends AbstractController
{
    /**
     * @Route("/", name="app_attachment_index", methods={"GET"})
     */
    public function index(AttachmentRepository $attachmentRepository, RegionRepository $regionRepository, NotificationRepository $notificationRepository): Response
    {
        $notifmenu = $notificationRepository->findBy(['statut'=>'non lu','addressee'=>$this->getUser()]);
        $regions = $regionRepository->findAll();
        $user = $this->getUser();
        return $this->render('attachment/index.html.twig', [
            'attachments' => $attachmentRepository->findAll(),
            'regions' => $regions,
            'user' => $user,
            'notifmenu'=>$notifmenu,
        ]);
    }

    /**
     * @Route("/new", name="app_attachment_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AttachmentRepository $attachmentRepository, RegionRepository $regionRepository, NotificationRepository $notificationRepository, FileUploader $fileUploader): Response
    {
        $notifmenu = $notificationRepository->findBy(['statut'=>'non lu','addressee'=>$this->getUser()]);
        $regions = $regionRepository->findAll();
        $user = $this->getUser();
        $attachment = new Attachment();
        $form = $this->createForm(AttachmentType::class, $attachment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $card = $form->get('card')->getData();
            if($card){
                $fileName = $fileUploader->upload($card);
                $attachment->setCard($fileName);
            }
            $cardVerso = $form->get('cardVerso')->getData();
            if($cardVerso){
                $fileName = $fileUploader->upload($cardVerso);
                $attachment->setCardVerso($fileName);
            }
            $attachmentRepository->add($attachment, true);

            return $this->redirectToRoute('app_attachment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('attachment/new.html.twig', [
            'attachment' => $attachment,
            'form' => $form,
            'regions' => $regions,
            'user' => $user,
            'notifmenu'=>$notifmenu,
        ]);
    }

    /**
     * @Route("/{id}", name="app_attachment_show", methods={"GET"})
     */
    public function show(Attachment $attachment, RegionRepository $regionRepository, NotificationRepository $notificationRepository): Response
    {
        $notifmenu = $notificationRepository->findBy(['statut'=>'non lu','addressee'=>$this->getUser()]);
        $regions = $regionRepository->findAll();
        $user = $this->getUser();
        return $this->render('attachment/show.html.twig', [
            'attachment' => $attachment,
            'regions' => $regions,
            'user' => $user,
            'notifmenu'=>$notifmenu,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_attachment_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Attachment $attachment, AttachmentRepository $attachmentRepository, RegionRepository $regionRepository, NotificationRepository $notificationRepository, FileUploader $fileUploader): Response
    {
        $notifmenu = $notificationRepository->findBy(['statut'=>'non lu','addressee'=>$this->getUser()]);
        $regions = $regionRepository->findAll();
        $user = $this->getUser();
        $form = $this->createForm(AttachmentType::class, $attachment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $card = $form->get('card')->getData();
            if($card){
                $fileName = $fileUploader->upload($card);
                $attachment->setCard($fileName);
            }
            $cardVerso = $form->get('cardVerso')->getData();
            if($cardVerso){
                $fileName = $fileUploader->upload($cardVerso);
                $attachment->setCardVerso($fileName);
            }
            $attachmentRepository->add($attachment, true);

            return $this->redirectToRoute('app_attachment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('attachment/edit.html.twig', [
            'attachment' => $attachment,
            'form' => $form,
            'regions' => $regions,
            'user' => $user,
            'notifmenu'=>$notifmenu,
        ]);
    }

    /**
     * @Route("/{id}", name="app_attachment_delete", methods={"POST"})
     */
    public function delete(Request $request, Attachment $attachment, AttachmentRepository $attachmentRepository): Response
    {
        
        if ($this->isCsrfTokenValid('delete'.$attachment->getId(), $request->request->get('_token'))) {
            $attachmentRepository->remove($attachment, true);
        }

        return $this->redirectToRoute('app_attachment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/attachment/_delete_form.html.twig
<form method="post" action="{{ path('app_attachment_delete', {'id': attachment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ attachment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/attachment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/attachment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Attachment{% endblock %}

{% block body %}
    <h1>Edit Attachment</h1>

    {{ include('attachment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_attachment_index') }}">back to list</a>

    {{ include('attachment/_delete_form.html.twig') }}
{% endblock %}

templates/attachment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attachment index{% endblock %}

{% block body %}
    <h1>Attachment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Is_a_character</th>
                <th>Full_name</th>
                <th>Cost</th>
                <th>Card</th>
                <th>CardVerso</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for attachment in attachments %}
            <tr>
                <td>{{ attachment.id }}</td>
                <td>{{ attachment.name }}</td>
                <td>{{ attachment.isACharacter ? 'Yes' : 'No' }}</td>
                <td>{{ attachment.fullName }}</td>
                <td>{{ attachment.cost }}</td>
                <td>{{ attachment.card }}</td>
                <td>{{ attachment.cardVerso }}</td>
                <td>
                    <a href="{{ path('app_attachment_show', {'id': attachment.id}) }}">show</a>
                    <a href="{{ path('app_attachment_edit', {'id': attachment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_attachment_new') }}">Create new</a>
{% endblock %}

templates/attachment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Attachment{% endblock %}

{% block body %}
    <h1>Create new Attachment</h1>

    {{ include('attachment/_form.html.twig') }}

    <a href="{{ path('app_attachment_index') }}">back to list</a>
{% endblock %}

templates/attachment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Attachment{% endblock %}

{% block body %}
    <h1>Attachment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ attachment.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ attachment.name }}</td>
            </tr>
            <tr>
                <th>Is_a_character</th>
                <td>{{ attachment.isACharacter ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Full_name</th>
                <td>{{ attachment.fullName }}</td>
            </tr>
            <tr>
                <th>Cost</th>
                <td>{{ attachment.cost }}</td>
            </tr>
            <tr>
                <th>Card</th>
                <td>{{ attachment.card }}</td>
            </tr>
            <tr>
                <th>CardVerso</th>
                <td>{{ attachment.cardVerso }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_attachment_index') }}">back to list</a>

    <a href="{{ path('app_attachment_edit', {'id': attachment.id}) }}">edit</a>

    {{ include('attachment/_delete_form.html.twig') }}
{% endblock %}